site_name: GPLGit

nav:
  - 🏠 Home: index.md
  - Woocoommerce:
    - Amazon: 'woocommerce/woocommerce-amazon.md'
    - Instagram: 'woocommerce/woocommerce-instagram.md'

theme:
  name: material

plugins:
  - tags
  - search

markdown_extensions:
  - attr_list